global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']
    scrape_interval: 15s
    metrics_path: '/apisix/prometheus/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

rule_files:
  # - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
